[logger.default]
level = "info"
[trace.jaeger] # 启用链路的核心配置
ServiceName = "waf-srv"
[server.http]
port = 9111
[http.ups]
addr = "http://127.0.0.1:9211" # 开启后并加上export EGO_DEBUG=true，可以看到每次http请求，配置名、地址、耗时、请求数据、响应数据
[http.waf]
addr = "http://127.0.0.1:9111" # 开启后并加上export EGO_DEBUG=true，可以看到每次http请求，配置名、地址、耗时、请求数据、响应数据
debug = true
[cron.waf]
enableDistributedTask = true			# 是否分布式任务，默认否，如果存在分布式任务，会只执行该定时任务
enableImmediatelyRun = false			# 是否立刻执行，默认否
enableSeconds = true				# 是否使用秒作解析器，默认否
spec = "*/1 * * * * *"					# 执行时间
delayExecType = "skip"					# skip，queue，concurrent，如果上一个任务执行较慢，到达了新任务执行时间，那么新任务选择跳过，排队，并发执行的策略，新任务默认选择skip策略
[redis.waf]
debug = false
addr = "127.0.0.1:6379"
[server.governor]
port = 9113
[mysql.waf]
connMaxLifetime = "300s"
debug = false
dsn = "root:123456@tcp(127.0.0.1:3306)/waf?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local"
level = "panic"
maxIdleConns = 50
maxOpenConns = 100
#[server.grpc]
#port = 9112
#enableAccessInterceptorReq = true
#enableAccessInterceptorRes = true
#[etcd]
#addrs=["127.0.0.1:2379"]
#[registry]
#connectTimeout = "1s"
#secure = false
#name = "wafs-srv"
#[grpc.upssrv]
#addr = "etcd:///ups-srv"