[server.http]
port = 9111
[redis.user]
debug = true
addr = "172.22.0.1:6479"
[server.grpc]
port = 9112
enableAccessInterceptorReq = true
enableAccessInterceptorRes = true
[server.governor]
port = 9113
#[etcd]
#addrs=["172.22.0.1:2379"]
#[registry]
#connectTimeout = "1s"
#secure = false
[mysql.waf]
connMaxLifetime = "300s"
debug = true
dsn = "root:123456@tcp(127.0.0.1:3306)/waf?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local"
level = "panic"
maxIdleConns = 50
maxOpenConns = 100
