[server.http]
port = 8111
[http.ups]
addr = "http://127.0.0.1:9111" # 开启后并加上export EGO_DEBUG=true，可以看到每次http请求，配置名、地址、耗时、请求数据、响应数据
debug = true
[redis.waf]
debug = true
addr = "127.0.0.1:6379"
enableAccessInterceptorReq = true
enableAccessInterceptorRes = true
[server.governor]
port = 8113
[mysql.waf]
connMaxLifetime = "300s"
debug = true
dsn = "root:123456@tcp(127.0.0.1:3306)/waf?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local"
level = "panic"
maxIdleConns = 50
maxOpenConns = 100
[grpc.upssrv]
addr = "etcd:///ups-srv"