[logger.default]
level = "info"
[trace.jaeger] # 启用链路的核心配置
ServiceName = "ups-srv"
[server.http]
port = 9211
[http.waf]
addr = "http://127.0.0.1:9111" # 开启后并加上export EGO_DEBUG=true，可以看到每次http请求，配置名、地址、耗时、请求数据、响应数据
[redis.ups]
debug = true
addr = "127.0.0.1:6379"
[server.governor]
port = 9213
[mysql.ups]
connMaxLifetime = "300s"
debug = true
dsn = "root:123456@tcp(127.0.0.1:3306)/ups?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local"
level = "panic"
maxIdleConns = 50
maxOpenConns = 100
#[server.grpc]
#port = 9212
#enableAccessInterceptorReq = true
#enableAccessInterceptorRes = true
#[etcd]
#addrs=["127.0.0.1:2379"]
#[registry]
#connectTimeout = "1s"
#secure = false
#name = "ups-srv"
