[server.http]
port = 9211
[redis.waf]
debug = true
addr = "127.0.0.1:6379"
#[server.grpc]
#port = 9212
enableAccessInterceptorReq = true
enableAccessInterceptorRes = true
[server.governor]
port = 9213
#[etcd]
#addrs=["127.0.0.1:2379"]
#[registry]
#connectTimeout = "1s"
#name = "ups_srv"
[mysql.waf]
connMaxLifetime = "300s"
debug = true
dsn = "root:123456@tcp(127.0.0.1:3306)/ups?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local"
level = "panic"
maxIdleConns = 50
maxOpenConns = 100
